
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: awx
    server: 'https://kubernetes.default.svc'
  source:
    path: addons/awx
    repoURL: 'https://github.com/niklaushirt/cp4waiops-gitops'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
