
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robot-shop
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: robot-shop
    server: 'https://kubernetes.default.svc'
  source:
    path: addons/robotshop
    repoURL: 'https://github.com/niklaushirt/cp4waiops-gitops'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
