
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: waiops-demo-ui
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: cp4waiops
    server: 'https://kubernetes.default.svc'
  source:
    path: addons/waiops-demo-ui
    repoURL: 'https://github.com/niklaushirt/cp4waiops-gitops'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
