
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cp4waiops-patch-topology-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "210"
  namespace: {{.Values.spec.aiManager.namespace}}
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          command:
            - /bin/sh
            - -c
            - |
              set -x

              while : ; do
                READY=$(oc get po -n {{.Values.spec.aiManager.namespace}} aiops-topology-merge)
                if [[ $? != 0 ]]; then
                  echo 'Topology Pods not ready yet.'
                  sleep 10s
                else
                  break
                fi
              done
              oc patch -n {{.Values.spec.aiManager.namespace}} serviceaccount aiops-topology-service-account -p '{"imagePullSecrets": [{"name": "ibm-entitlement-key"}]}'
              oc delete pod $(oc get po -n {{.Values.spec.aiManager.namespace}}|grep ImagePull|awk '{print$1}') -n {{.Values.spec.aiManager.namespace}}

              oc patch deployment aiops-topology-merge -n {{.Values.spec.aiManager.namespace}} -p '{"spec": {"template": {"spec": {"containers": {"livenessProbe": {"failureThreshold": 62}}}}}}'


 

      restartPolicy: Never
      serviceAccountName: openshift-argocd-admin-ai
  backoffLimit: 4
