{{- if .Values.solutions.ELKInstall }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: openshift-logging
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/2_addons/elk
    repoURL: 'https://github.com/niklaushirt/cp4waiops-gitops'
    targetRevision: 3.2-dev
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      #- Validate=false
      - SkipDryRunOnMissingResource=true
      - FailOnSharedResource=true
      #- CreateNamespace=true
{{- end }}