---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-capture
  namespace: default
  labels:
      app:  webhook-capture
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  webhook-capture
  template:
    metadata:
      labels:
        app:  webhook-capture
    spec:
      containers:
      - image: niklaushirt/webhook-capture:1.0
        imagePullPolicy: IfNotPresent
        name: gateway
        command:
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "250m"
            memory: "250Mi"
---
apiVersion: v1
kind: Service
metadata:
  name:  webhook-capture-service
  namespace: default
spec:
  selector:
    app:  webhook-capture
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name:  webhook-capture
  namespace: default
spec:
  to:
    kind: Service
    name:  webhook-capture-service
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name:  webhook-capture-webhook
  namespace: default
spec:
  path: /webhook
  to:
    kind: Service
    name:  webhook-capture-service
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name:  webhook-capture-history
  namespace: default
spec:
  path: /history
  to:
    kind: Service
    name:  webhook-capture-service
